// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEuer7Tx76z2adB-ZoiOBa1b1x7-GYrZ4',
    appId: '1:292094966479:android:8fd37e039c41231cfe55ba',
    messagingSenderId: '292094966479',
    projectId: 'test-46f4a',
    databaseURL: 'https://test-46f4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-46f4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK7hCE7FO2EP37_ULrwkjhSjRgjpFb5_8',
    appId: '1:292094966479:ios:2005b9a105c7edb2fe55ba',
    messagingSenderId: '292094966479',
    projectId: 'test-46f4a',
    databaseURL: 'https://test-46f4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-46f4a.firebasestorage.app',
    iosClientId: '292094966479-lrpc7dhd7n8i1bmec145s15u2piluo0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.health',
  );
}
